import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'


export default function Home() {
  const [colorInfo, setColorInfo ] = useState('rgba(207, 206, 206, 0.2)');
  useEffect(() => {
    const script = document.createElement('script');
  
    script.src = "game.js";
    script.async = true;
  
    document.body.appendChild(script);
  
    return () => {
      document.body.removeChild(script);
    }
  }, []);

  const changeColor = () =>{
    const colorArray = ['rgba(207, 206, 206, 0.2)','rgba(209, 113, 113, 0.2)','rgba(216, 218, 114, 0.2)','rgba(123, 233, 120, 0.2)','rgba(120, 229, 233, 0.2)','rgba(233, 120, 227, 0.2)']
    const num = Math.floor(Math.random()*colorArray.length);
    console.log(num);
    console.log(colorArray[num]);
    setColorInfo(colorArray[num]);

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script src="//cdn.jsdelivr.net/npm/phaser@3.55.2/dist/phaser.min.js"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/*Phaser*/}
        <div className={styles.phaserCover}></div>

        <div className={styles.phaserContain}></div>

        {/*Blog*/}
        <div className={styles.appBody}>
              <h1>Latest News</h1>
              <div className={styles.post}>
                <div className={styles.postContent}>
                <h1>SWEETHEART</h1>
                <img style={{float:"right", margin: "10px"}} src='https://scontent-bru2-1.xx.fbcdn.net/v/t1.6435-9/57433623_10214693663276087_6310669398759702528_n.jpg?_nc_cat=106&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=cwTCFxmyo3MAX_5VlL_&_nc_ht=scontent-bru2-1.xx&oh=34f0d60cabf8be54c9abc881caa508ea&oe=61271F58' width='50%'></img>
                <p>I always knew you were the one for me. No, it is not because you connect with me on a deeper level than others. The truth is, I have shared only had few connections with others in the past. But with you, I feel complete. I have peace and inexplicable joy. I swear by the breath in me that I will never give you up for any reason because that would be the end of me. Even after death, I believe we will be connected eternally. I love you forever, and that is the only thing that matters.</p>
                </div>
              </div>
              <div className={styles.post}>
                <div className={styles.postContent}>
                  <h1>BABY</h1>
                  <img style={{float:"left", margin: "10px"}} src='https://scontent-bru2-1.xx.fbcdn.net/v/t1.6435-9/50813557_10214117136343274_5004158850035613696_n.jpg?_nc_cat=101&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=T-kZ3I3IDfYAX-rjNEd&_nc_ht=scontent-bru2-1.xx&oh=4da5858892c00b8e0ad4d490552fdb4d&oe=61251195' width='50%'></img>
                  <p>I hope you never doubt my love and intentions for you. As the stars light up the night sky, so does your love for me light up my world. Regardless of the time and day, you will always have my unquestioning love and loyalty. I love loving you, and nothing can change that. I believe in you, and I believe in us. So, never, ever lose hope because we have a beautiful future ahead. Remember that we have each other’s back so, we can’t afford to get distracted by trivialities that may bring regrettable results. I cherish you, now and always. Don’t forget that.</p>
                </div>
              </div>
              <div className={styles.post}>
                <div className={styles.postContent}>
                  <h1>MINE</h1>
                  <img style={{float:"right", margin: "10px"}} src='https://scontent-bru2-1.xx.fbcdn.net/v/t1.6435-9/46112802_10213591567204374_8262361112826085376_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=0debeb&_nc_ohc=euMlMpjOINoAX8Igk5o&_nc_ht=scontent-bru2-1.xx&oh=274b791924750e161914f05dc2e7e55c&oe=6124A5CF' width='50%'></img>
                  <p>Meeting you was the beginning of a 360 degrees turnaround for my life. I have become humble and accomplished ever since you came around. In essence, your presence changed my life. The best part about it is that I didn’t expect to fall for you this hard. All I know is that I never want to go back to the person I was because there’s no sweeter life than the one you’ve given me. The day I met you was divine, and I hope that someday, we will officially make it a day worth celebrating in our lives. Thank you for everything you’ve done for me. I believe our love will echo throughout humanity’s existence.</p>
                </div>
              </div>

              <div className={styles.post}>
                <div className={styles.postContent}>
                <h1>First Post</h1>
                <img style={{float:"right", margin: "10px"}} src='https://scontent-bru2-1.xx.fbcdn.net/v/t1.6435-9/57433623_10214693663276087_6310669398759702528_n.jpg?_nc_cat=106&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=cwTCFxmyo3MAX_5VlL_&_nc_ht=scontent-bru2-1.xx&oh=34f0d60cabf8be54c9abc881caa508ea&oe=61271F58' width='50%'></img>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy
                 text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                </div>
              </div>
              <div className={styles.post}>
                <div className={styles.postContent}>
                  <h1>Second Post</h1>
                  <img style={{float:"left", margin: "10px"}} src='https://scontent-bru2-1.xx.fbcdn.net/v/t1.6435-9/50813557_10214117136343274_5004158850035613696_n.jpg?_nc_cat=101&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=T-kZ3I3IDfYAX-rjNEd&_nc_ht=scontent-bru2-1.xx&oh=4da5858892c00b8e0ad4d490552fdb4d&oe=61251195' width='50%'></img>
                  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                </div>
              </div>
              <div className={styles.post}>
                <div className={styles.postContent}>
                  <h1>Third Post</h1>
                  <img style={{float:"right", margin: "10px"}} src='https://scontent-bru2-1.xx.fbcdn.net/v/t1.6435-9/46112802_10213591567204374_8262361112826085376_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=0debeb&_nc_ohc=euMlMpjOINoAX8Igk5o&_nc_ht=scontent-bru2-1.xx&oh=274b791924750e161914f05dc2e7e55c&oe=6124A5CF' width='50%'></img>
                  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                </div>
              </div>
          
        </div>
        
      </main>
      <main style={{minWidth:"320px", width:"100%", height:"100vh", backgroundColor: 'white'}} onClick={()=>{changeColor()}}>
          <div className={styles.myInfoPanel}>
          <svg className={styles.nextPic} width="15%" viewBox="0 0 148 90" version="1.1" xmlnsXlink="http://www.w3.org/1999/xlink"><path d="M34.992 23.495h27.855v2.219H37.546v16.699h23.792v2.219H37.546v18.334h25.591v2.219H34.992v-41.69zm30.35 0h2.96l13.115 18.334 13.405-18.334L113.055.207 83.1 43.756l15.436 21.429H95.46L81.417 45.683 67.316 65.185h-3.018L79.85 43.756 65.343 23.495zm34.297 2.219v-2.219h31.742v2.219h-14.623v39.47h-2.554v-39.47H99.64zM.145 23.495h3.192l44.011 66.003L29.16 65.185 2.814 26.648l-.116 38.537H.145v-41.69zm130.98 38.801c-.523 0-.914-.405-.914-.928 0-.524.391-.929.913-.929.528 0 .913.405.913.929 0 .523-.385.928-.913.928zm2.508-2.443H135c.019.742.56 1.24 1.354 1.24.888 0 1.391-.535 1.391-1.539v-6.356h1.391v6.362c0 1.808-1.043 2.849-2.77 2.849-1.62 0-2.732-1.01-2.732-2.556zm7.322-.08h1.379c.118.853.95 1.395 2.149 1.395 1.117 0 1.937-.58 1.937-1.377 0-.685-.521-1.097-1.708-1.377l-1.155-.28c-1.62-.38-2.36-1.166-2.36-2.487 0-1.602 1.304-2.668 3.26-2.668 1.82 0 3.15 1.066 3.23 2.58h-1.354c-.13-.828-.85-1.346-1.894-1.346-1.1 0-1.832.53-1.832 1.34 0 .642.472 1.01 1.64 1.284l.987.243c1.838.43 2.596 1.178 2.596 2.53 0 1.72-1.33 2.799-3.453 2.799-1.987 0-3.323-1.029-3.422-2.637z" fill="#000" fillRule="nonzero"></path></svg>
            <img className={styles.reactPic} width='15%' src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ288L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K"></img>
            <div className={styles.myInfo} style={{backgroundColor: `${colorInfo}`, transition: "background-color 0.5s"}}>
              <h1>The secret of getting ahead is getting started.</h1>
              <p>"My name is Doan and I am a self-taught front-end developer with a lot of curiosity. I started my adventure with designing
                 and coding websites as a teenager and since then I'm developing my skills constantly. Programming is not only a passion, but
                  also my medecine. Yes, sometimes I feel like interacting with machines is easier than with people <img width='25px' height='25px' src="https://img.icons8.com/color/48/000000/smiling.png"/>. 
                  Thanks to my detail-oriented personnality, I'm able to build complete web applications. 
                  Thats why, despite the fact that front-end is the apple of my eye in most projects I work rather as a full-stack developer."</p>
            </div>
            
            <img className={styles.myPic} width="20%" src='https://res.cloudinary.com/hg7nb1gfv/image/upload/v1627444567/bpu9fk8zdajvsdfpy65b.png'></img>
            
          </div>

      </main>
    </div>
  )
}
